context:
  name: pixi-gui
  version: "${{ env.get('PIXI_GUI_VERSION', default='0.1.0dev') }}"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ".."

build:
  number: 0
  script:
    - if: osx
      then:
        # WebKit framework linking for macOS, see https://crates.io/crates/wry/0.37.0
        - export RUSTFLAGS="-l framework=WebKit"
    - if: unix
      then:
        - export RUSTC_WRAPPER=sccache
        - unset CI
        - TARGET=${TARGET:-$(rustc -vV | grep "host:" | awk '{print $2}')}
        - export CARGO_TARGET_DIR=${{ SRC_DIR }}/../../target-cache
        - pnpm install
        - pnpm run tauri build --no-bundle
        - mkdir -p ${{ PREFIX }}/bin
        - install -m0755 "$CARGO_TARGET_DIR/$TARGET/release/pixi-gui" "${{ PREFIX }}/bin"
        - cd ${{ SRC_DIR }}/src-tauri && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

        # menuinst
        - mkdir -p "${{ PREFIX }}/Menu"
        - if: osx
          then:
            - sed "s/__PKG_VERSION__/${PKG_VERSION}/g" "${{ RECIPE_DIR }}/menu.json" > "${{ PREFIX }}/Menu/${{ PKG_NAME }}_menu.json"
            - install -m0644 "${{ SRC_DIR }}/src-tauri/icons/icon.icns" "${{ PREFIX }}/Menu/icon.icns"
        - if: linux
          then:
            - install -m0644 "${{ RECIPE_DIR }}/menu.json" "${{ PREFIX }}/Menu/${{ PKG_NAME }}_menu.json"
            - install -m0644 "${{ SRC_DIR }}/src-tauri/icons/icon.png" "${{ PREFIX }}/Menu/icon.png"
    - if: win
      then:
        # Required to fix "path too long" issues
        - if not "%GITHUB_ACTIONS%"=="" if not exist C:\\cargo-home mkdir C:\\cargo-home
        - if not "%GITHUB_ACTIONS%"=="" set CARGO_HOME=C:\\cargo-home

        - set RUSTC_WRAPPER=sccache
        - set CI=
        - set CARGO_TARGET_DIR=%SRC_DIR%\..\..\target-cache
        - cmd /c "pnpm install"
        - cmd /c "pnpm run tauri build --no-bundle"
        - cmd /c "if not exist %PREFIX%\bin\ mkdir %PREFIX%\bin\"
        - cp %CARGO_TARGET_DIR%\release\pixi-gui.exe %PREFIX%\bin
        - cd %SRC_DIR%\src-tauri && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

        # menuinst
        - mkdir "%PREFIX%\Menu"
        - copy /Y "%RECIPE_DIR%\menu.json" "%PREFIX%\Menu\%PKG_NAME%_menu.json"
        - copy /Y "%SRC_DIR%\src-tauri\icons\icon.ico" "%PREFIX%\Menu\icon.ico"

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses
    - nodejs
    - pnpm
    - sccache
    - if: linux
      then:
        - pkg-config
        - make
  host:
    - if: linux
      then:
        - cairo
        - expat
        - fontconfig
        - glib
        - gtk3
        - libsoup
        - pango
        - webkit2gtk4.1 >=2.48.5
        - xorg-xorgproto
        - zlib
