/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as WorkspacePathIndexRouteImport } from "./routes/workspace.$path/index";
import { Route as WorkspacePathProcessRouteImport } from "./routes/workspace.$path/process";
import { Route as WorkspacePathRouteRouteImport } from "./routes/workspace.$path/route";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspacePathRouteRoute = WorkspacePathRouteRouteImport.update({
  id: "/workspace/$path",
  path: "/workspace/$path",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspacePathIndexRoute = WorkspacePathIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspacePathRouteRoute,
} as any);
const WorkspacePathProcessRoute = WorkspacePathProcessRouteImport.update({
  id: "/process",
  path: "/process",
  getParentRoute: () => WorkspacePathRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/workspace/$path": typeof WorkspacePathRouteRouteWithChildren;
  "/workspace/$path/process": typeof WorkspacePathProcessRoute;
  "/workspace/$path/": typeof WorkspacePathIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/workspace/$path/process": typeof WorkspacePathProcessRoute;
  "/workspace/$path": typeof WorkspacePathIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/workspace/$path": typeof WorkspacePathRouteRouteWithChildren;
  "/workspace/$path/process": typeof WorkspacePathProcessRoute;
  "/workspace/$path/": typeof WorkspacePathIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/workspace/$path"
    | "/workspace/$path/process"
    | "/workspace/$path/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/workspace/$path/process" | "/workspace/$path";
  id:
    | "__root__"
    | "/"
    | "/workspace/$path"
    | "/workspace/$path/process"
    | "/workspace/$path/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WorkspacePathRouteRoute: typeof WorkspacePathRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workspace/$path": {
      id: "/workspace/$path";
      path: "/workspace/$path";
      fullPath: "/workspace/$path";
      preLoaderRoute: typeof WorkspacePathRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workspace/$path/": {
      id: "/workspace/$path/";
      path: "/";
      fullPath: "/workspace/$path/";
      preLoaderRoute: typeof WorkspacePathIndexRouteImport;
      parentRoute: typeof WorkspacePathRouteRoute;
    };
    "/workspace/$path/process": {
      id: "/workspace/$path/process";
      path: "/process";
      fullPath: "/workspace/$path/process";
      preLoaderRoute: typeof WorkspacePathProcessRouteImport;
      parentRoute: typeof WorkspacePathRouteRoute;
    };
  }
}

interface WorkspacePathRouteRouteChildren {
  WorkspacePathProcessRoute: typeof WorkspacePathProcessRoute;
  WorkspacePathIndexRoute: typeof WorkspacePathIndexRoute;
}

const WorkspacePathRouteRouteChildren: WorkspacePathRouteRouteChildren = {
  WorkspacePathProcessRoute: WorkspacePathProcessRoute,
  WorkspacePathIndexRoute: WorkspacePathIndexRoute,
};

const WorkspacePathRouteRouteWithChildren =
  WorkspacePathRouteRoute._addFileChildren(WorkspacePathRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspacePathRouteRoute: WorkspacePathRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
